name: let-him-cook
services:
  postgres:
    image: postgres:14
    container_name: let-him-cook-postgres
    restart: always
    ports:
      - 5432:5432
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'tscout']
      interval: 30s
      timeout: 20s
      retries: 3
    environment:
      POSTGRES_PASSWORD: let-him-cook
      POSTGRES_USER: let-him-cook
      POSTGRES_DB: let-him-cook
