export enum EnumInjectServiceToken {
  VOTE_SERVICE = 'VOTE_SERVICE',
  USER_SERVICE = 'USER_SERVICE',
  INGREDIENT_SERVICE = 'INGREDIENT_SERVICE',
  DISH_SERVICE = 'DISH_SERVICE',
  AUTH_SERVICE = 'AUTH_SERVICE',
}
