export enum TypeOfFood {
  VEGETABLE = 'VEGETABLE',
  FRUIT = 'FRUIT',
  MEAT = 'MEAT',
  SEAFOOD = 'SEAFOOD',
  CEREAL = 'CEREAL',
  TUBER = 'TUBER',
  LEGUME = 'LEGUME',
  DAIRY = 'DAIRY',
  OTHER = 'OTHER',
}
